@tool

const KEY_DEFAULT_BLOCK = "DEFAULT_BLOCK"
const KEY_DIALOGUE_END="DIALOGUE_END"
const KEY_DIALOGUE_LOADED="DIALOGUE_LOADED"
const KEY_DIALOGUE_NOT_LOADED="DIALOGUE_NOT_LOADED"
# player
const KEY_PLAYER_BLOCK_SELECTION_TOOLTIP = "PLAYER_BLOCK_SELECTION_TOOLTIP"
const KEY_PLAYER_RESTART_TOOLTIP = "PLAYER_RESTART_TOOLTIP"
const KEY_PLAYER_NEXT_LINE_TOOLTIP = "PLAYER_NEXT_LINE_TOOLTIP"
const KEY_PLAYER_FORWARD_TOOLTIP = "PLAYER_FORWARD_TOOLTIP"
const KEY_PLAYER_POLTERGEIST_TOOLTIP = "PLAYER_POLTERGEIST_TOOLTIP"
const KEY_PLAYER_CLEAR_MEM_TOOLTIP = "PLAYER_CLEAR_MEM_TOOLTIP"
const KEY_PLAYER_BALLOONS_TOOLTIP = "PLAYER_BALLOONS_TOOLTIP"
const KEY_PLAYER_SHOW_META_TOOLTIP = "PLAYER_SHOW_META_TOOLTIP"
const KEY_PLAYER_SHOW_DEBUG_TOOLTIP = "PLAYER_SHOW_DEBUG_TOOLTIP"
const KEY_PLAYER_DIALOGUE_STARTED = "PLAYER_DIALOGUE_STARTED_MESSAGE"

const KEY_HELP_ONLINE_DOCS = "HELP_ONLINE_DOCS"
const KEY_HELP_REPORT_ISSUE = "HELP_REPORT_ISSUE"
const KEY_HELP_ABOUT = "HELP_ABOUT"
const KEY_DEBUG_PANEL_NAME = "DEBUG_PANEL_NAME"
const KEY_DEBUG_VARIABLES_LABEL = "DEBUG_VARIABLES_LABEL"
const KEY_DEBUG_EXT_VARIABLES_LABEL = "DEBUG_EXT_VARIABLES_LABEL"
const KEY_DEBUG_HISTORY_LABEL = "DEBUG_HISTORY_LABEL"
const KEY_DEBUG_EVENT_LABEL = "DEBUG_EVENT_LABEL"
const KEY_DEBUG_VARIABLE_LABEL = "DEBUG_VARIABLE_LABEL"
const KEY_DEBUG_EXTERNAL_VARIABLE_LABEL = "DEBUG_EXTERNAL_VARIABLE_LABEL"
const KEY_DEBUG_TIME = "DEBUG_TIME"
const KEY_DEBUG_TYPE = "DEBUG_TYPE"
const KEY_DEBUG_NAME = "DEBUG_NAME"
const KEY_DEBUG_VALUE = "DEBUG_VALUE"
const KEY_DEBUG_PREVIOUS_VALUE = "DEBUG_PREVIOUS_VALUE"
const KEY_DEBUG_EDIT = "DEBUG_EDIT"
const KEY_DEBUG_SAVE = "DEBUG_SAVE"
const KEY_DEBUG_REMOVE = "DEBUG_REMOVE"
const KEY_DEBUG_CANCEL = "DEBUG_CANCEL"
const KEY_DEBUG_ADD_VARIABLE = "DEBUG_ADD_VARIABLE"
const KEY_GENERATE_LINE_IDS = "GENERATE_LINE_IDS"
const KEY_CREATE_CSV = "CREATE_CSV"

const KEY_CSV_EXPORTER_WINDOW_TITLE = "CSV_EXPORTER_WINDOW_TITLE"
const KEY_CSV_EXPORTER_NEW_FILE = "CSV_EXPORTER_NEW_FILE"
const KEY_CSV_EXPORTER_NEW_FILE_DESC = "CSV_EXPORTER_NEW_FILE_DESC"
const KEY_CSV_EXPORTER_INCLUDE_METADATA = "CSV_EXPORTER_INCLUDE_METADATA"
const KEY_CSV_EXPORTER_INCLUDE_METADATA_DESC = "CSV_EXPORTER_INCLUDE_METADATA_DESC"
const KEY_CSV_EXPORTER_INCLUDE_HEADER = "CSV_EXPORTER_INCLUDE_HEADER"
const KEY_CSV_EXPORTER_INCLUDE_HEADER_DESC = "CSV_EXPORTER_INCLUDE_HEADER_DESC"
const KEY_CSV_EXPORTER_HEADER_LOCALE = "CSV_EXPORTER_HEADER_LOCALE"
const KEY_CSV_EXPORTER_HEADER_LOCALE_DESC = "CSV_EXPORTER_HEADER_LOCALE_DESC"
const KEY_CSV_EXPORTER_DELIMITER = "CSV_EXPORTER_DELIMITER"
const KEY_CSV_EXPORTER_DELIMITER_DESC = "CSV_EXPORTER_DELIMITER_DESC"
const KEY_CSV_EXPORTER_SOURCE_FILE = "CSV_EXPORTER_SOURCE_FILE"
const KEY_CSV_EXPORTER_FILE = "CSV_EXPORTER_FILE"
const KEY_CSV_EXPORTER_OPTIONS = "CSV_EXPORTER_OPTIONS"
const KEY_CSV_EXPORTER_EXPORT = "CSV_EXPORTER_EXPORT"
const KEY_CSV_FILE_EXISTS_WARNING = "CSV_FILE_EXISTS_WARNING"
const KEY_CSV_EXPORTER_SUCCEED = "CSV_EXPORTER_SUCCEED"
const KEY_CSV_EXPORTER_FAIL = "CSV_EXPORTER_FAIL"
const KEY_CSV_EXPORTER_NOTE = "CSV_EXPORTER_NOTE"
const KEY_CSV_EXPORTER_SOURCE_FILE_NOT_FOUND = "CSV_EXPORTER_SOURCE_FILE_NOT_FOUND"
const KEY_CSV_EXPORTER_FILE_PARSE_FAIL = "KEY_CSV_EXPORTER_FILE_PARSE_FAIL"
const KEY_FILE_NOT_FOUND = "FILE_NOT_FOUND"

const KEY_DIALOGUE_PLAYER= "DIALOGUE_PLAYER"
const KEY_OPEN_IN_DIALOGUE_PLAYER = "OPEN_IN_DIALOGUE_PLAYER"
const KEY_PLAYER_OPEN_MENU = "PLAYER_OPEN_MENU"
const KEY_PLAYER_FOLLOW_LINE = "PLAYER_FOLLOW_LINE"
const KEY_PLAYER_WATCH_FILE = "PLAYER_WATCH_FILE"
const KEY_PLAYER_ACTION_BAR_MOVE_TOP = "PLAYER_ACTION_BAR_MOVE_TOP"
const KEY_PLAYER_ACTION_BAR_MOVE_BOTTOM = "PLAYER_ACTION_BAR_MOVE_BOTTOM"
const KEY_PLAYER_STATUS_SUCCESS = "PLAYER_STATUS_SUCCESS"
const KEY_PLAYER_STATUS_FAIL = "PLAYER_STATUS_FAIL"
const KEY_PLAYER_STATUS_LOADING = "PLAYER_STATUS_LOADING"
const KEY_OPEN_DIALOGUE_PLAYER = "OPEN_DIALOGUE_PLAYER"

const KEY_WRONG_FILE_FORMAT_TITLE = "WRONG_FILE_FORMAT_TITLE"
const KEY_WRONG_FILE_FORMAT_MESSAGE = "WRONG_FILE_FORMAT_MESSAGE"

const KEY_ABOUT_WINDOW_TITLE = "ABOUT_WINDOW_TITLE"
const KEY_ABOUT_TITLE = "ABOUT_TITLE"
const KEY_ABOUT_DESCRIPTION = "ABOUT_DESCRIPTION"

const KEY_PLUGIN_HELP_AND_INFO = "PLUGIN_HELP_AND_INFO"
const KEY_VIEW_LICENSE = "VIEW_LICENSE"
const KEY_BACK = "BACK"
const KEY_EDITOR = "EDITOR"
const KEY_PLAYER = "PLAYER"
const KEY_DEBUGGER = "DEBUGGER"
const KEY_TOOLS = "TOOLS"
const KEY_LANGUAGE = "LANGUAGE"

static var plugin_version := ""
static var initialized := false
static var _loaded_locale := "en"
static var _default_locale := "en"

static var _entries = {}
static var _fallback = {}

const TRANSLATIONS_PATH: String = "res://addons/clyde/editor/config/translations/%s.csv"


static func get_string(key: String) -> String:
	if _entries.has(key):
		return _entries[key]
	return _fallback[key]


static func load_strings_for_current_locale(translations_path: String = TRANSLATIONS_PATH) -> void:
	var locale = TranslationServer.get_tool_locale()

	_load_entries_from_file(
		translations_path % _default_locale,
		_fallback
	)

	var locale_file = translations_path % locale

	if locale != _default_locale and FileAccess.file_exists(locale_file):
		_load_entries_from_file(locale_file, _entries)
	else:
		_entries = _fallback
	_loaded_locale = locale
	initialized = true

static func _load_entries_from_file(translation_file_path: String, dictionary: Dictionary) -> void:
	var file = FileAccess.open(translation_file_path, FileAccess.READ)
	var header = file.get_csv_line()
	if header.size() < 2:
		return

	while file.get_position() < file.get_length():
		var line = file.get_csv_line()
		if line.size() < 2:
			continue
		dictionary[line[0]] = line[1]
	return
